# Methods compiled for the first render of a Qt canvas (GLMakie screens of
# type Screen{QMLMakie.QMLWindow}), which the precompile workload cannot run
# without a GL context. Generated with `julia --trace-compile=out.jl` around
# planar_window, keeping lines that mention QML/QMLMakie/GLMakie/HammerheadGUI
# and no anonymous functions. Stale lines are skipped; regenerate after
# GLMakie/QMLMakie upgrades if window startup slows down.
precompile(Tuple{Type{Base.KeySet{K, T} where T<:(Base.AbstractDict{K, V} where V) where K}, Base.Dict{GLMakie.Screen{GLWindow} where GLWindow, Nothing}})
precompile(Tuple{Type{ComputePipeline.TypedEdge{InputTuple, OutputTuple, F} where F where OutputTuple where InputTuple}, ComputePipeline.ComputeEdge{ComputePipeline.ComputeGraph}, typeof(GLMakie.generate_indices), NamedTuple{(:gl_projected_positions,), Tuple{Base.RefValue{Array{GeometryBasics.Point{4, Float32}, 1}}}}})
precompile(Tuple{Type{ComputePipeline.TypedEdge{InputTuple, OutputTuple, F} where F where OutputTuple where InputTuple}, ComputePipeline.ComputeEdge{ComputePipeline.ComputeGraph}, typeof(GLMakie.generate_indices), NamedTuple{(:positions_transformed_f32c,), Tuple{Base.RefValue{Array{GeometryBasics.Point{2, Float32}, 1}}}}})
precompile(Tuple{Type{GLMakie.GLAbstraction.RenderObject{GLMakie.GLAbstraction.StandardPrerender}}, QMLMakie.QMLWindow, Base.Dict{Symbol, Any}, Array{Observables.Observable{T} where T, 1}, GLMakie.GLAbstraction.GLVertexArray{GLMakie.GLAbstraction.GLBuffer{GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}}}, GLMakie.GLAbstraction.StandardPrerender, Nothing, Bool})
precompile(Tuple{Type{GLMakie.GLAbstraction.RenderObject{GLMakie.GLAbstraction.StandardPrerender}}, QMLMakie.QMLWindow, Base.Dict{Symbol, Any}, Array{Observables.Observable{T} where T, 1}, GLMakie.GLAbstraction.GLVertexArray{GLMakie.GLAbstraction.GLBuffer{UInt32}}, GLMakie.GLAbstraction.StandardPrerender, Nothing, Bool})
precompile(Tuple{Type{GLMakie.GLAbstraction.RenderObject{GLMakie.GLAbstraction.StandardPrerender}}, QMLMakie.QMLWindow, Base.Dict{Symbol, Any}, Array{Observables.Observable{T} where T, 1}, GLMakie.GLAbstraction.GLVertexArray{Int64}, GLMakie.GLAbstraction.StandardPrerender, Nothing, Bool})
precompile(Tuple{Type{GLMakie.GLAbstraction.RenderObject{GLMakie.PostprocessPrerender}}, QMLMakie.QMLWindow, Base.Dict{Symbol, Any}, Array{Observables.Observable{T} where T, 1}, GLMakie.GLAbstraction.GLVertexArray{Int64}, GLMakie.PostprocessPrerender, Nothing, Observables.Observable{Bool}})
precompile(Tuple{Type{GLMakie.GLAbstraction.RenderObject{Pre} where Pre}, Base.Dict{Symbol, Any}, GLMakie.GLAbstraction.LazyShader, GLMakie.PostprocessPrerender, Nothing, QMLMakie.QMLWindow})
precompile(Tuple{Type{GLMakie.GLAbstraction.RenderObject{Pre} where Pre}, Base.Dict{Symbol, Any}, GLMakie.GLVisualizeShader, GLMakie.GLAbstraction.StandardPrerender, Nothing, QMLMakie.QMLWindow})
precompile(Tuple{Type{GLMakie.GLAbstraction.StandardPostrenderInstanced}, Int32, GLMakie.GLAbstraction.GLVertexArray{GLMakie.GLAbstraction.GLBuffer{GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}}}, UInt32})
precompile(Tuple{Type{GLMakie.GLAbstraction.StandardPrerender}, Bool, Bool})
precompile(Tuple{Type{HammerheadGUI.PlanarShell}, HammerheadGUI.Controllers.PlanarWorkflow})
precompile(Tuple{Type{Int64}, QML.ItemDataRole})
precompile(Tuple{Type{Pair{A, B} where B where A}, Symbol, GLMakie.GLAbstraction.Texture{ColorTypes.RGBA{FixedPointNumbers.Normed{UInt8, 8}}, 2}})
precompile(Tuple{Type{Pair{A, B} where B where A}, Symbol, GLMakie.GLAbstraction.Texture{ColorTypes.RGBA{Float16}, 2}})
precompile(Tuple{Type{Pair{A, B} where B where A}, Symbol, GLMakie.GLAbstraction.Texture{FixedPointNumbers.Normed{UInt8, 8}, 2}})
precompile(Tuple{Type{Pair{A, B} where B where A}, Symbol, GLMakie.GLAbstraction.Texture{GeometryBasics.Vec{2, UInt32}, 2}})
precompile(Tuple{Type{Pair{A, B} where B where A}, UInt32, GLMakie.GLAbstraction.Texture{ColorTypes.RGBA{FixedPointNumbers.Normed{UInt8, 8}}, 2}})
precompile(Tuple{Type{Pair{A, B} where B where A}, UInt32, GLMakie.GLAbstraction.Texture{ColorTypes.RGBA{Float16}, 2}})
precompile(Tuple{Type{Pair{A, B} where B where A}, UInt32, GLMakie.GLAbstraction.Texture{FixedPointNumbers.Normed{UInt8, 8}, 2}})
precompile(Tuple{Type{Pair{A, B} where B where A}, UInt32, GLMakie.GLAbstraction.Texture{GeometryBasics.Vec{2, UInt32}, 2}})
precompile(Tuple{Type{Ptr{GLMakie.GLAbstraction.DepthStencil_24_8}}, Ptr{Nothing}})
precompile(Tuple{Type{QML.ArgcArgv}, Array{String, 1}})
precompile(Tuple{Type{QML.QByteArrayDereferenced}, Ptr{Nothing}})
precompile(Tuple{Type{QML.QGuiApplication}, Base.RefValue{Int32}, CxxWrap.CxxWrapCore.CxxPtr{CxxWrap.CxxWrapCore.CxxPtr{CxxWrap.CxxWrapCore.CxxChar}}})
precompile(Tuple{Type{QML.QString}, String})
precompile(Tuple{Type{QML.QVariant}, Bool})
precompile(Tuple{Type{QML.QVariant}, Float64})
precompile(Tuple{Type{QML.QVariant}, Int64})
precompile(Tuple{Type{QML.QVariant}, String})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), Type{Int32}, NTuple{16, QML.ItemDataRole}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), Type{Int32}, NTuple{29, QML.MouseButton}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), Type{Int32}, NTuple{37, QML.Format}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), Type{Int32}, NTuple{4, QML.ImageType}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), Type{Int32}, NTuple{468, QML.Key}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), Type{Int32}, NTuple{8, QML.GraphicsAPI}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), Type{Int32}, Tuple{QML.ObjectOwnership, QML.ObjectOwnership}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), Type{Int32}, Tuple{QML.Orientation, QML.Orientation}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), Type{Symbol}, NTuple{16, QML.ItemDataRole}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), Type{Symbol}, NTuple{29, QML.MouseButton}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), Type{Symbol}, NTuple{37, QML.Format}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), Type{Symbol}, NTuple{4, QML.ImageType}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), Type{Symbol}, NTuple{468, QML.Key}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), Type{Symbol}, NTuple{8, QML.GraphicsAPI}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), Type{Symbol}, Tuple{QML.ObjectOwnership, QML.ObjectOwnership}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), Type{Symbol}, Tuple{QML.Orientation, QML.Orientation}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), typeof(Base.:(==)), Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, Type{Int32}, Tuple{NTuple{16, QML.ItemDataRole}}}, Array{Int32, 1}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), typeof(Base.:(==)), Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, Type{Int32}, Tuple{NTuple{29, QML.MouseButton}}}, Array{Int32, 1}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), typeof(Base.:(==)), Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, Type{Int32}, Tuple{NTuple{37, QML.Format}}}, Array{Int32, 1}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), typeof(Base.:(==)), Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, Type{Int32}, Tuple{NTuple{4, QML.ImageType}}}, Array{Int32, 1}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), typeof(Base.:(==)), Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, Type{Int32}, Tuple{NTuple{468, QML.Key}}}, Array{Int32, 1}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), typeof(Base.:(==)), Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, Type{Int32}, Tuple{NTuple{8, QML.GraphicsAPI}}}, Array{Int32, 1}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), typeof(Base.:(==)), Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, Type{Int32}, Tuple{Tuple{QML.ObjectOwnership, QML.ObjectOwnership}}}, Array{Int32, 1}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), typeof(Base.:(==)), Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, Type{Int32}, Tuple{Tuple{QML.Orientation, QML.Orientation}}}, Array{Int32, 1}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), typeof(Base.:(==)), Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, Type{Symbol}, Tuple{NTuple{16, QML.ItemDataRole}}}, Array{Symbol, 1}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), typeof(Base.:(==)), Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, Type{Symbol}, Tuple{NTuple{29, QML.MouseButton}}}, Array{Symbol, 1}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), typeof(Base.:(==)), Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, Type{Symbol}, Tuple{NTuple{37, QML.Format}}}, Array{Symbol, 1}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), typeof(Base.:(==)), Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, Type{Symbol}, Tuple{NTuple{4, QML.ImageType}}}, Array{Symbol, 1}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), typeof(Base.:(==)), Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, Type{Symbol}, Tuple{NTuple{468, QML.Key}}}, Array{Symbol, 1}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), typeof(Base.:(==)), Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, Type{Symbol}, Tuple{NTuple{8, QML.GraphicsAPI}}}, Array{Symbol, 1}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), typeof(Base.:(==)), Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, Type{Symbol}, Tuple{Tuple{QML.ObjectOwnership, QML.ObjectOwnership}}}, Array{Symbol, 1}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), typeof(Base.:(==)), Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, Type{Symbol}, Tuple{Tuple{QML.Orientation, QML.Orientation}}}, Array{Symbol, 1}})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Base.:(==)), Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, Type{Int32}, Tuple{NTuple{16, QML.ItemDataRole}}}, Array{Int32, 1}}}})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Base.:(==)), Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, Type{Int32}, Tuple{NTuple{29, QML.MouseButton}}}, Array{Int32, 1}}}})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Base.:(==)), Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, Type{Int32}, Tuple{NTuple{37, QML.Format}}}, Array{Int32, 1}}}})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Base.:(==)), Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, Type{Int32}, Tuple{NTuple{4, QML.ImageType}}}, Array{Int32, 1}}}})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Base.:(==)), Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, Type{Int32}, Tuple{NTuple{468, QML.Key}}}, Array{Int32, 1}}}})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Base.:(==)), Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, Type{Int32}, Tuple{NTuple{8, QML.GraphicsAPI}}}, Array{Int32, 1}}}})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Base.:(==)), Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, Type{Int32}, Tuple{Tuple{QML.ObjectOwnership, QML.ObjectOwnership}}}, Array{Int32, 1}}}})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Base.:(==)), Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, Type{Int32}, Tuple{Tuple{QML.Orientation, QML.Orientation}}}, Array{Int32, 1}}}})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Base.:(==)), Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, Type{Symbol}, Tuple{NTuple{16, QML.ItemDataRole}}}, Array{Symbol, 1}}}})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Base.:(==)), Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, Type{Symbol}, Tuple{NTuple{29, QML.MouseButton}}}, Array{Symbol, 1}}}})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Base.:(==)), Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, Type{Symbol}, Tuple{NTuple{37, QML.Format}}}, Array{Symbol, 1}}}})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Base.:(==)), Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, Type{Symbol}, Tuple{NTuple{4, QML.ImageType}}}, Array{Symbol, 1}}}})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Base.:(==)), Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, Type{Symbol}, Tuple{NTuple{468, QML.Key}}}, Array{Symbol, 1}}}})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Base.:(==)), Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, Type{Symbol}, Tuple{NTuple{8, QML.GraphicsAPI}}}, Array{Symbol, 1}}}})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Base.:(==)), Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, Type{Symbol}, Tuple{Tuple{QML.ObjectOwnership, QML.ObjectOwnership}}}, Array{Symbol, 1}}}})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Base.:(==)), Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, Type{Symbol}, Tuple{Tuple{QML.Orientation, QML.Orientation}}}, Array{Symbol, 1}}}})
precompile(Tuple{typeof(Base.Iterators._zip_iterate_interleave), Tuple{Tuple{Base.Multimedia.MIME{:var"image/svg+xml"}, Int64}, Tuple{typeof(QML.load_svg), Int64}}, Tuple{}, Tuple{Base.Missing, Base.Missing}})
precompile(Tuple{typeof(Base.argtail), Tuple{typeof(QML.load_svg), typeof(QML.load_png)}})
precompile(Tuple{typeof(Base.cconvert), Type{QML.QByteArrayDereferenced}, QML.QByteArrayAllocated})
precompile(Tuple{typeof(Base.convert), Type{QML.QString}, String})
precompile(Tuple{typeof(Base.delete!), Base.Dict{CxxWrap.CxxWrapCore.ConstCxxPtr{QML.QQmlContext}, Array{Any, 1}}, CxxWrap.CxxWrapCore.ConstCxxPtr{QML.QQmlContext}})
precompile(Tuple{typeof(Base.delete!), Base.Set{GLMakie.Screen{GLWindow} where GLWindow}, GLMakie.Screen{QMLMakie.QMLWindow}})
precompile(Tuple{typeof(Base.getindex), Base.Dict{CxxWrap.CxxWrapCore.ConstCxxPtr{QML.QQmlContext}, Array{Any, 1}}, CxxWrap.CxxWrapCore.ConstCxxPtr{QML.QQmlContext}})
precompile(Tuple{typeof(Base.getproperty), Base.Iterators.Zip{Tuple{Tuple{Base.Multimedia.MIME{:var"image/svg+xml"}, Base.Multimedia.MIME{:var"image/png"}}, Tuple{typeof(QML.load_svg), typeof(QML.load_png)}}}, Symbol})
precompile(Tuple{typeof(Base.getproperty), Base.KeySet{Any, Base.Dict{Any, Tuple{GLMakie.GLAbstraction.Texture{Float16, 2}, Function}}}, Symbol})
precompile(Tuple{typeof(Base.getproperty), Base.KeySet{GLMakie.Screen{GLWindow} where GLWindow, Base.Dict{GLMakie.Screen{GLWindow} where GLWindow, Nothing}}, Symbol})
precompile(Tuple{typeof(Base.getproperty), GLMakie.Screen{QMLMakie.QMLWindow}, Symbol})
precompile(Tuple{typeof(Base.getproperty), HammerheadGUI.Controllers.RunState, Symbol})
precompile(Tuple{typeof(Base.getproperty), QML.QVariantAllocated, Symbol})
precompile(Tuple{typeof(Base.haskey), Base.Dict{CxxWrap.CxxWrapCore.ConstCxxPtr{QML.QQmlContext}, Array{Any, 1}}, CxxWrap.CxxWrapCore.ConstCxxPtr{QML.QQmlContext}})
precompile(Tuple{typeof(Base.indexed_iterate), Tuple{Base.Multimedia.MIME{:var"image/png"}, typeof(QML.load_png)}, Int64})
precompile(Tuple{typeof(Base.indexed_iterate), Tuple{Base.Multimedia.MIME{:var"image/svg+xml"}, typeof(QML.load_svg)}, Int64, Int64})
precompile(Tuple{typeof(Base.indexed_iterate), Tuple{Base.Multimedia.MIME{:var"image/svg+xml"}, typeof(QML.load_svg)}, Int64})
precompile(Tuple{typeof(Base.indexed_iterate), Tuple{Makie.TextureAtlas, QMLMakie.QMLWindow}, Int64, Int64})
precompile(Tuple{typeof(Base.indexed_iterate), Tuple{Makie.TextureAtlas, QMLMakie.QMLWindow}, Int64})
precompile(Tuple{typeof(Base.instances), Type{QML.Key}})
precompile(Tuple{typeof(Base.isequal), Tuple{Array{GLMakie.ShaderSource, 1}, Array{Array{String, 1}, 1}}, Tuple{Array{GLMakie.ShaderSource, 1}, Array{Array{String, 1}, 1}}})
precompile(Tuple{typeof(Base.iterate), Base.Iterators.Zip{Tuple{Tuple{Base.Multimedia.MIME{:var"image/svg+xml"}, Base.Multimedia.MIME{:var"image/png"}}, Tuple{typeof(QML.load_svg), typeof(QML.load_png)}}}, Tuple{Int64, Int64}})
precompile(Tuple{typeof(Base.length), GLMakie.GLAbstraction.GLBuffer{GeometryBasics.Point{4, Float32}}})
precompile(Tuple{typeof(Base.pop!), Base.Dict{Any, Tuple{GLMakie.GLAbstraction.Texture{Float16, 2}, Function}}, Tuple{Makie.TextureAtlas, QMLMakie.QMLWindow}})
precompile(Tuple{typeof(Base.push!), GLMakie.Screen{QMLMakie.QMLWindow}, Makie.Scene, GLMakie.GLAbstraction.RenderObject{GLMakie.GLAbstraction.StandardPrerender}})
precompile(Tuple{typeof(Base.setindex!), Base.Dict{CxxWrap.CxxWrapCore.ConstCxxPtr{QML.QQmlContext}, Array{Any, 1}}, Array{Any, 1}, CxxWrap.CxxWrapCore.ConstCxxPtr{QML.QQmlContext}})
precompile(Tuple{typeof(Base.setindex!), Base.Dict{String, GLMakie.GLAbstraction.GLBuffer{T} where T}, GLMakie.GLAbstraction.GLBuffer{GeometryBasics.Point{4, Float32}}, String})
precompile(Tuple{typeof(Base.setindex!), Base.RefValue{ComputePipeline.TypedEdge{InputTuple, OutputTuple, F} where F where OutputTuple where InputTuple}, ComputePipeline.TypedEdge{NamedTuple{(:gl_projected_positions,), Tuple{Base.RefValue{Array{GeometryBasics.Point{4, Float32}, 1}}}}, Tuple{Base.RefValue{Array{UInt32, 1}}, Base.RefValue{Array{Float32, 1}}}, typeof(GLMakie.generate_indices)}})
precompile(Tuple{typeof(Base.setindex!), QML.QHashAllocated{Int32, QML.QByteArray}, String, Int64})
precompile(Tuple{typeof(Base.setindex!), QML._JuliaPropertyMapAllocated, Bool, String})
precompile(Tuple{typeof(Base.setindex!), QML._JuliaPropertyMapAllocated, Float64, String})
precompile(Tuple{typeof(Base.setindex!), QML._JuliaPropertyMapAllocated, Int64, String})
precompile(Tuple{typeof(Base.setindex!), QML._JuliaPropertyMapAllocated, Makie.Figure, String})
precompile(Tuple{typeof(Base.setindex!), QML._JuliaPropertyMapAllocated, String, String})
precompile(Tuple{typeof(Base.unsafe_convert), Type{QML.QByteArrayDereferenced}, QML.QByteArrayDereferenced})
precompile(Tuple{typeof(ComputePipeline.resolve!), ComputePipeline.TypedEdge{NamedTuple{(:gl_projected_positions,), Tuple{Base.RefValue{Array{GeometryBasics.Point{4, Float32}, 1}}}}, Tuple{Base.RefValue{Array{UInt32, 1}}, Base.RefValue{Array{Float32, 1}}}, typeof(GLMakie.generate_indices)}})
precompile(Tuple{typeof(Core.kwcall), NamedTuple{(:app, :stepModel, :passModel), Tuple{QML.JuliaPropertyMap, QML.JuliaItemModelAllocated, QML.JuliaItemModelAllocated}}, typeof(QML.loadqml), String})
precompile(Tuple{typeof(Core.kwcall), NamedTuple{(:start_renderloop,), Tuple{Bool}}, typeof(GLMakie.apply_config!), GLMakie.Screen{QMLMakie.QMLWindow}, GLMakie.ScreenConfig})
precompile(Tuple{typeof(Core.kwcall), NamedTuple{(:view,), Tuple{Base.Dict{String, String}}}, Type{GLMakie.GLVisualizeShader}, GLMakie.Screen{QMLMakie.QMLWindow}, String, Vararg{String}})
precompile(Tuple{typeof(Core.memoryref), GenericMemory{:not_atomic, HammerheadGUI.PassRow, Core.AddrSpace{Core}(0x00)}})
precompile(Tuple{typeof(Core.memoryref), GenericMemory{:not_atomic, Tuple{Int64, UInt16, GLMakie.GLAbstraction.RenderObject{Pre} where Pre}, Core.AddrSpace{Core}(0x00)}})
precompile(Tuple{typeof(CxxWrap.CxxWrapCore.delete), QML.JuliaItemModelAllocated})
precompile(Tuple{typeof(CxxWrap.CxxWrapCore.delete), QML.QByteArrayAllocated})
precompile(Tuple{typeof(CxxWrap.CxxWrapCore.delete), QML.QGuiApplicationAllocated})
precompile(Tuple{typeof(CxxWrap.CxxWrapCore.delete), QML.QHashAllocated{Int32, QML.QByteArray}})
precompile(Tuple{typeof(CxxWrap.CxxWrapCore.delete), QML.QListAllocated{Int32}})
precompile(Tuple{typeof(CxxWrap.CxxWrapCore.delete), QML.QListAllocated{QML.QByteArray}})
precompile(Tuple{typeof(CxxWrap.CxxWrapCore.delete), QML.QSizeAllocated})
precompile(Tuple{typeof(CxxWrap.CxxWrapCore.delete), QML.QStringAllocated})
precompile(Tuple{typeof(CxxWrap.CxxWrapCore.delete), QML.QVariantAllocated})
precompile(Tuple{typeof(CxxWrap.CxxWrapCore.delete), QML._JuliaPropertyMapAllocated})
precompile(Tuple{typeof(CxxWrap.CxxWrapCore.dereference_argument), CxxWrap.CxxWrapCore.CxxPtr{QML.QObject}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.bind), GLMakie.GLAbstraction.GLBuffer{GeometryBasics.Point{4, Float32}}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.compile_shader), QMLMakie.QMLWindow, GLMakie.ShaderSource, String})
precompile(Tuple{typeof(GLMakie.GLAbstraction.get_template!), GLMakie.GLAbstraction.ShaderCache, GLMakie.ShaderSource, Base.Dict{String, String}, Base.Dict{Symbol, Any}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, Array{GeometryBasics.Vec{4, Float32}, 1}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, Bool})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, ColorTypes.RGBA{Float32}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, Float32})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, GLMakie.GLAbstraction.GLBuffer{GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, GLMakie.GLAbstraction.GLBuffer{GeometryBasics.Point{2, Float32}}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, GLMakie.GLAbstraction.Texture{ColorTypes.RGBA{FixedPointNumbers.Normed{UInt8, 8}}, 2}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, GLMakie.GLAbstraction.Texture{ColorTypes.RGBA{Float16}, 2}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, GLMakie.GLAbstraction.Texture{FixedPointNumbers.Normed{UInt8, 8}, 2}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, GLMakie.GLAbstraction.Texture{Float32, 1}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, GLMakie.GLAbstraction.Texture{GeometryBasics.Vec{2, UInt32}, 2}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, GeometryBasics.Vec{2, Float32}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, GeometryBasics.Vec{3, Float32}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, Int32})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, Int64})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, Observables.Observable{GeometryBasics.Vec{2, Float32}}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, StaticArraysCore.SArray{Tuple{2, 3}, Float32, 2, 6}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, StaticArraysCore.SArray{Tuple{3, 3}, Float32, 2, 9}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, StaticArraysCore.SArray{Tuple{4, 4}, Float32, 2, 16}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, Type{GLMakie.GLAbstraction.GLBuffer{T} where T}, Array{ColorTypes.RGBA{Float32}, 1}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, Type{GLMakie.GLAbstraction.GLBuffer{T} where T}, Array{Float32, 1}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, Type{GLMakie.GLAbstraction.GLBuffer{T} where T}, Array{GeometryBasics.Point{2, Float32}, 1}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, Type{GLMakie.GLAbstraction.GLBuffer{T} where T}, Array{GeometryBasics.Point{3, Float32}, 1}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, Type{GLMakie.GLAbstraction.GLBuffer{T} where T}, Array{GeometryBasics.Point{4, Float32}, 1}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, Type{GLMakie.GLAbstraction.GLBuffer{T} where T}, Array{GeometryBasics.Vec{2, Float32}, 1}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, Type{GLMakie.GLAbstraction.GLBuffer{T} where T}, Array{GeometryBasics.Vec{3, Float32}, 1}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, Type{GLMakie.GLAbstraction.GLBuffer{T} where T}, Array{GeometryBasics.Vec{4, Float32}, 1}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, Type{GLMakie.GLAbstraction.GLBuffer{T} where T}, Array{Makie.Quaternion{Float32}, 1}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, Type{GLMakie.GLAbstraction.GLBuffer{T} where T}, GeometryBasics.Vec{2, Float32}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, Type{GLMakie.GLAbstraction.GLBuffer{T} where T}, GeometryBasics.Vec{3, Float32}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, Type{GLMakie.GLAbstraction.GLBuffer{T} where T}, GeometryBasics.Vec{4, Float32}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, Type{GLMakie.GLAbstraction.Texture{T, NDIM} where NDIM where T<:Union{Real, ColorTypes.Colorant{T, N} where N where T, Makie.Quaternion{T} where T, StaticArraysCore.StaticArray{Tuple{N}, T, 1} where T where N}}, GLMakie.GLAbstraction.Texture{ColorTypes.RGBA{Float32}, 1}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, Type{GLMakie.GLAbstraction.Texture{T, NDIM} where NDIM where T<:Union{Real, ColorTypes.Colorant{T, N} where N where T, Makie.Quaternion{T} where T, StaticArraysCore.StaticArray{Tuple{N}, T, 1} where T where N}}, GLMakie.GLAbstraction.Texture{Float16, 2}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, Type{GLMakie.GLAbstraction.Texture{T, NDIM} where NDIM where T<:Union{Real, ColorTypes.Colorant{T, N} where N where T, Makie.Quaternion{T} where T, StaticArraysCore.StaticArray{Tuple{N}, T, 1} where T where N}}, GLMakie.GLAbstraction.Texture{Float32, 2}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, Type{GLMakie.GLAbstraction.Texture{T, NDIM} where NDIM where T<:Union{Real, ColorTypes.Colorant{T, N} where N where T, Makie.Quaternion{T} where T, StaticArraysCore.StaticArray{Tuple{N}, T, 1} where T where N}}, ShaderAbstractions.Sampler{Float16, 1, Array{Float16, 1}}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, UInt32})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, typeof(GLMakie.GLAbstraction.indexbuffer), Array{GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}, 1}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, typeof(GLMakie.to_index_buffer), Array{UInt32, 1}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_convert), QMLMakie.QMLWindow, typeof(GLMakie.to_index_buffer), Int64})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gl_switch_context!), QMLMakie.QMLWindow})
precompile(Tuple{typeof(GLMakie.GLAbstraction.gluniform), Int32, Int64, GLMakie.GLAbstraction.Texture{Float16, 1}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.require_context), QMLMakie.QMLWindow, QMLMakie.QMLWindow})
precompile(Tuple{typeof(GLMakie.GLAbstraction.resize_nocopy!), GLMakie.GLAbstraction.Texture{ColorTypes.RGBA{FixedPointNumbers.Normed{UInt8, 8}}, 2}, Tuple{Int64, Int64}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.resize_nocopy!), GLMakie.GLAbstraction.Texture{ColorTypes.RGBA{Float16}, 2}, Tuple{Int64, Int64}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.resize_nocopy!), GLMakie.GLAbstraction.Texture{FixedPointNumbers.Normed{UInt8, 8}, 2}, Tuple{Int64, Int64}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.resize_nocopy!), GLMakie.GLAbstraction.Texture{GLMakie.GLAbstraction.DepthStencil_24_8, 2}, Tuple{Int64, Int64}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.resize_nocopy!), GLMakie.GLAbstraction.Texture{GeometryBasics.Vec{2, UInt32}, 2}, Tuple{Int64, Int64}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.texparameter), GLMakie.GLAbstraction.Texture{Float16, 1}, UInt32, UInt32})
precompile(Tuple{typeof(GLMakie.GLAbstraction.toglsltype_string), GLMakie.GLAbstraction.GLBuffer{GeometryBasics.Point{4, Float32}}})
precompile(Tuple{typeof(GLMakie.GLAbstraction.toglsltype_string), GLMakie.GLAbstraction.Texture{Float16, 1}})
precompile(Tuple{typeof(GLMakie.closeall)})
precompile(Tuple{typeof(GLMakie.draw_atomic), GLMakie.Screen{QMLMakie.QMLWindow}, Makie.Scene, Makie.Plot{Makie.heatmap, Tuple{Array{Float64, 1}, Array{Float64, 1}, Array{Float32, 2}}}})
precompile(Tuple{typeof(GLMakie.draw_atomic), GLMakie.Screen{QMLMakie.QMLWindow}, Makie.Scene, Makie.Plot{Makie.lines, Tuple{Array{GeometryBasics.Point{2, Float32}, 1}}}})
precompile(Tuple{typeof(GLMakie.draw_atomic), GLMakie.Screen{QMLMakie.QMLWindow}, Makie.Scene, Makie.Plot{Makie.lines, Tuple{Array{GeometryBasics.Point{2, Float64}, 1}}}})
precompile(Tuple{typeof(GLMakie.draw_atomic), GLMakie.Screen{QMLMakie.QMLWindow}, Makie.Scene, Makie.Plot{Makie.linesegments, Tuple{Array{GeometryBasics.Point{2, Float32}, 1}}}})
precompile(Tuple{typeof(GLMakie.draw_atomic), GLMakie.Screen{QMLMakie.QMLWindow}, Makie.Scene, Makie.Plot{Makie.linesegments, Tuple{Array{GeometryBasics.Point{3, Float32}, 1}}}})
precompile(Tuple{typeof(GLMakie.draw_atomic), GLMakie.Screen{QMLMakie.QMLWindow}, Makie.Scene, Makie.Plot{Makie.mesh, Tuple{GeometryBasics.Mesh{2, Float64, GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}, (:position, :normal), Tuple{Array{GeometryBasics.Point{2, Float64}, 1}, Array{GeometryBasics.Vec{3, Float32}, 1}}, Array{GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}, 1}}}}})
precompile(Tuple{typeof(GLMakie.draw_atomic), GLMakie.Screen{QMLMakie.QMLWindow}, Makie.Scene, Makie.Plot{Makie.mesh, Tuple{GeometryBasics.Mesh{2, Float64, GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}, (:position,), Tuple{Array{GeometryBasics.Point{2, Float64}, 1}}, Array{GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}, 1}}}}})
precompile(Tuple{typeof(GLMakie.draw_atomic), GLMakie.Screen{QMLMakie.QMLWindow}, Makie.Scene, Makie.Plot{Makie.scatter, Tuple{Array{GeometryBasics.Point{2, Float32}, 1}}}})
precompile(Tuple{typeof(GLMakie.draw_atomic), GLMakie.Screen{QMLMakie.QMLWindow}, Makie.Scene, Makie.Plot{Makie.text, Tuple{Array{GeometryBasics.Point{2, Float32}, 1}}}})
precompile(Tuple{typeof(GLMakie.draw_linesegments), Any, Array{GeometryBasics.Point{2, Float32}, 1}, Base.Dict{K, V} where V where K})
precompile(Tuple{typeof(GLMakie.draw_linesegments), Any, Array{GeometryBasics.Point{3, Float32}, 1}, Base.Dict{K, V} where V where K})
precompile(Tuple{typeof(GLMakie.register_robj!), Function, GLMakie.Screen{QMLMakie.QMLWindow}, Makie.Scene, Makie.Plot{Makie.heatmap, Tuple{Array{Float64, 1}, Array{Float64, 1}, Array{Float32, 2}}}, Array{Symbol, 1}, Array{Symbol, 1}, Base.Dict{Symbol, Symbol}})
precompile(Tuple{typeof(GLMakie.register_robj!), Function, GLMakie.Screen{QMLMakie.QMLWindow}, Makie.Scene, Makie.Plot{Makie.lines, Tuple{Array{GeometryBasics.Point{2, Float32}, 1}}}, Array{Symbol, 1}, Array{Symbol, 1}, Base.Dict{Symbol, Symbol}})
precompile(Tuple{typeof(GLMakie.register_robj!), Function, GLMakie.Screen{QMLMakie.QMLWindow}, Makie.Scene, Makie.Plot{Makie.lines, Tuple{Array{GeometryBasics.Point{2, Float64}, 1}}}, Array{Symbol, 1}, Array{Symbol, 1}, Base.Dict{Symbol, Symbol}})
precompile(Tuple{typeof(GLMakie.register_robj!), Function, GLMakie.Screen{QMLMakie.QMLWindow}, Makie.Scene, Makie.Plot{Makie.linesegments, Tuple{Array{GeometryBasics.Point{2, Float32}, 1}}}, Array{Symbol, 1}, Array{Symbol, 1}, Base.Dict{Symbol, Symbol}})
precompile(Tuple{typeof(GLMakie.register_robj!), Function, GLMakie.Screen{QMLMakie.QMLWindow}, Makie.Scene, Makie.Plot{Makie.linesegments, Tuple{Array{GeometryBasics.Point{3, Float32}, 1}}}, Array{Symbol, 1}, Array{Symbol, 1}, Base.Dict{Symbol, Symbol}})
precompile(Tuple{typeof(GLMakie.register_robj!), Function, GLMakie.Screen{QMLMakie.QMLWindow}, Makie.Scene, Makie.Plot{Makie.mesh, Tuple{GeometryBasics.Mesh{2, Float64, GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}, (:position, :normal), Tuple{Array{GeometryBasics.Point{2, Float64}, 1}, Array{GeometryBasics.Vec{3, Float32}, 1}}, Array{GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}, 1}}}}, Array{Symbol, 1}, Array{Symbol, 1}, Base.Dict{Symbol, Symbol}})
precompile(Tuple{typeof(GLMakie.register_robj!), Function, GLMakie.Screen{QMLMakie.QMLWindow}, Makie.Scene, Makie.Plot{Makie.mesh, Tuple{GeometryBasics.Mesh{2, Float64, GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}, (:position,), Tuple{Array{GeometryBasics.Point{2, Float64}, 1}}, Array{GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}, 1}}}}, Array{Symbol, 1}, Array{Symbol, 1}, Base.Dict{Symbol, Symbol}})
precompile(Tuple{typeof(GLMakie.register_robj!), Function, GLMakie.Screen{QMLMakie.QMLWindow}, Makie.Scene, Makie.Plot{Makie.scatter, Tuple{Array{GeometryBasics.Point{2, Float32}, 1}}}, Array{Symbol, 1}, Array{Symbol, 1}, Base.Dict{Symbol, Symbol}})
precompile(Tuple{typeof(GLMakie.register_robj!), Function, GLMakie.Screen{QMLMakie.QMLWindow}, Makie.Scene, Makie.Plot{Makie.text, Tuple{Array{GeometryBasics.Point{2, Float32}, 1}}}, Array{Symbol, 1}, Array{Symbol, 1}, Base.Dict{Symbol, Symbol}})
precompile(Tuple{typeof(GLMakie.scale_factor), QMLMakie.QMLWindow})
precompile(Tuple{typeof(GLMakie.to_opengl_mesh!), QMLMakie.QMLWindow, Base.Dict{Symbol, Any}, GeometryBasics.Mesh{2, Float32, GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}, (:position,), Tuple{Array{GeometryBasics.Point{2, Float32}, 1}}, Array{GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}, 1}}})
precompile(Tuple{typeof(GLMakie.was_destroyed), QMLMakie.QMLWindow})
precompile(Tuple{typeof(HammerheadGUI._qt_init!)})
precompile(Tuple{typeof(HammerheadGUI.hh_tick)})
precompile(Tuple{typeof(HammerheadGUI.planar_window), HammerheadGUI.Controllers.PlanarWorkflow})
precompile(Tuple{typeof(Observables.listeners), Observables.Observable{Union{Nothing, HammerheadGUI.Controllers.ResultExplorer}}})
precompile(Tuple{typeof(QML.__init__)})
precompile(Tuple{typeof(QML.addLibraryPath), String})
precompile(Tuple{typeof(QML.clear), QML._JuliaPropertyMapAllocated, String})
precompile(Tuple{typeof(QML.colcount), QML.ItemModelData{Array{HammerheadGUI.PassRow, 1}}})
precompile(Tuple{typeof(QML.colcount), QML.ItemModelData{Array{HammerheadGUI.StepRow, 1}}})
precompile(Tuple{typeof(QML.connect_value_changed), QML._JuliaPropertyMapAllocated, QML.JuliaPropertyMap, Function})
precompile(Tuple{typeof(QML.data), QML.ItemModelData{Array{HammerheadGUI.PassRow, 1}}, Int32, Int32, Int32})
precompile(Tuple{typeof(QML.data), QML.ItemModelData{Array{HammerheadGUI.StepRow, 1}}, Int32, Int32, Int32})
precompile(Tuple{typeof(QML.force_model_update), QML.JuliaItemModelAllocated})
precompile(Tuple{typeof(QML.get_julia_call)})
precompile(Tuple{typeof(QML.julia_call), Function, Ptr{Nothing}})
precompile(Tuple{typeof(QML.nextroleindex), QML.QHashAllocated{Int32, QML.QByteArray}})
precompile(Tuple{typeof(QML.on_context_destroyed), CxxWrap.CxxWrapCore.CxxRef{CxxWrap.CxxWrapCore.CxxPtr{QML.QObject}}})
precompile(Tuple{typeof(QML.qputenv), String, QML.QByteArrayAllocated})
precompile(Tuple{typeof(QML.rolenames), QML.ItemModelData{Array{HammerheadGUI.PassRow, 1}}})
precompile(Tuple{typeof(QML.rolenames), QML.ItemModelData{Array{HammerheadGUI.StepRow, 1}}})
precompile(Tuple{typeof(QML.rowcount), QML.ItemModelData{Array{HammerheadGUI.PassRow, 1}}})
precompile(Tuple{typeof(QML.rowcount), QML.ItemModelData{Array{HammerheadGUI.StepRow, 1}}})
precompile(Tuple{typeof(QML.set_context_property), CxxWrap.CxxWrapCore.CxxPtr{QML.QQmlContext}, String, QML.JuliaItemModelAllocated})
precompile(Tuple{typeof(QML.set_context_property), QML.QQmlContextDereferenced, String, QML._JuliaPropertyMapAllocated})
precompile(Tuple{typeof(QML.set_julia_value), QML._JuliaPropertyMapAllocated, QML.JuliaPropertyMap})
precompile(Tuple{typeof(QML.value), Type{Any}, QML.QVariantDereferenced})
precompile(Tuple{typeof(QML.value), Type{CxxWrap.CxxWrapCore.CxxBool}, QML.QVariantDereferenced})
precompile(Tuple{typeof(QML.value), Type{CxxWrap.CxxWrapCore.CxxPtr{QML.QObject}}, QML.QVariantDereferenced})
precompile(Tuple{typeof(QML.value), Type{Float64}, QML.QVariantDereferenced})
precompile(Tuple{typeof(QML.values), QML.QHashAllocated{Int32, QML.QByteArray}})
precompile(Tuple{typeof(QMLMakie.dpi_changed), Makie.Figure, Float64, QML.QObjectDereferenced})
precompile(Tuple{typeof(QMLMakie.on_window_close), Makie.Figure})
precompile(Tuple{typeof(QMLMakie.qmlwindow), GLMakie.Screen{QMLMakie.QMLWindow}})
precompile(Tuple{typeof(QMLMakie.renderfunction), GLMakie.Screen{QMLMakie.QMLWindow}, Makie.Figure})
precompile(Tuple{typeof(QMLMakie.set_focus), Makie.Figure, Bool})
precompile(Tuple{typeof(QMLMakie.setup_screen), CxxWrap.CxxWrapCore.CxxPtr{QML.QOpenGLFramebufferObject}, CxxWrap.CxxWrapCore.CxxPtr{QML.QQuickWindow}})
precompile(Tuple{typeof(QMLMakie.setup_screen), GLMakie.Screen{QMLMakie.QMLWindow}, CxxWrap.CxxWrapCore.CxxPtr{QML.QOpenGLFramebufferObject}})
precompile(Tuple{typeof(ShaderAbstractions.context_alive), QMLMakie.QMLWindow})
precompile(Tuple{typeof(ShaderAbstractions.native_context_alive), QMLMakie.QMLWindow})
