name: CI
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    permissions: # needed to allow julia-actions/cache to proactively delete old caches that it has created
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        version:
          - 'lts'
          - '1'
          - 'pre'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          prefix: xvfb-run -s '-screen 0 1024x768x24'
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      # --------------------------------------------------------
      # 0. checkout + install everything you already had …
      # --------------------------------------------------------

      # 1. Install a virtual frame-buffer **and** some basic GL libs
      - name: Install Xvfb & Mesa
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              xvfb mesa-utils libgl1 libglu1-mesa

      # 2. Configure the docs environment **inside Xvfb**
      - name: Configure doc environment
        run: |
          xvfb-run -s '-screen 0 1024x768x24' \
            julia --project=docs --color=yes -e '
              using Pkg;
              Pkg.develop(PackageSpec(path=pwd()));
              Pkg.instantiate();'

      # 3. Build the package (still needs X)
      - uses: julia-actions/julia-buildpkg@v1
        with:
          prefix: xvfb-run

      # 4. Build & deploy the docs — pass a **short** prefix
      - uses: julia-actions/julia-docdeploy@v1
        with:
          prefix: xvfb-run          # no extra flags here!
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 5. Doctests (again under Xvfb)
      - name: Run doctests
        run: |
          xvfb-run -s '-screen 0 1024x768x24' \
            julia --project=docs --color=yes -e '
              using Documenter: DocMeta, doctest
              using Hammerhead
              DocMeta.setdocmeta!(Hammerhead, :DocTestSetup,
                                  :(using Hammerhead); recursive=true)
              doctest(Hammerhead)'

